var rarray = new Uint32Array(5);
do {window.crypto.getRandomValues(rarray);
for (var i = 0; i < rarray.length; i++) { rarray[i]=(rarray[i]%13);}
console.log("Your lucky numbers:"); for (var i = 0; i < rarray.length; i++) { console.log(rarray[i]);}
} while( rarray[1]==rarray[2]|| rarray[1]==rarray[3]||rarray[1]==rarray[4]||rarray[1]==rarray[0]||rarray[2]==rarray[3]||rarray[2]==rarray[4]||rarray[0]==rarray[2]||rarray[3]==rarray[4]||rarray[3]==rarray[0]|| rarray[4]==rarray[0])


var queText= [
["<h4> What happens to a Planet as it is located farther away from the Sun: </h4>", "<div><button  class='primary-button-correct'> a). Its orbital period increases.</button></div>", "<div><button class='primary-button'>b). Its orbital period decreases.</button></div>","<div><button  class='primary-button'>c). Its orbital period is constant.</button></div>","<div><button  class='primary-button'>d). Its rotational period is increased.</button></div>", "Description: As the distance of a planet from the sun increases, its orbital speed decreases, which causes longer orbital periods."],
["<h4> Which planet is mostly made up of ice:</h4>", "<div><button  class='primary-button'>a). Jupiter</button></div>", "<div><button  class='primary-button'>b). Saturn</button></div>","<div><button  class='primary-button'>c). Mars</button></div>","<div><button  class='primary-button-correct'>d). Uranus</button></div>", "Description: Jupiter and Saturn are gaseous giants, Mars is a terrestrial planet and Uranus is an ice giant."],
["<h4> What are the objects made of ice, rock and dust that glow near the Sun?</h4>", "<div><button  class='primary-button'>a). Asteroids</button></div>", "<div><button  class='primary-button-correct'>b). Comets</button></div>","<div><button  class='primary-button'>c). Outer planets</button></div>","<div><button  class='primary-button'>d). Meteors</button></div>", "Description: Comets are snowballs made up of frozen gas, rock, and dust that orbit the Sun. As they get closer to the Sun, they heat up and leave a trail of glowing dust and gases."],
["<h4> What are the groups of stars, gases, and dusts held together by gravity?</h4>", "<div><button  class='primary-button-correct'>a). Galaxy</button></div>", "<div><button  class='primary-button'>b). Constellation</button></div>","<div><button  class='primary-button'>c). Community</button></div>","<div><button  class='primary-button'>d). TNSTC</button></div>", "Galaxy is a group of stars, dust etc bound by gravitation, Constellations are a group of stars which form a pattern or a picture, Community is a group of people and TNSTC is  'Tamilnadu Science and Technology Centre'"],
["<h4> If a small rocky particle comes from Space to Earth’s atmosphere, and before striking the ground, it doesn’t burn up, it’s most likely _____?</h4>", "<div><button  class='primary-button'>a). Meteoroid</button></div>", "<div><button class='primary-button-correct'>b). Meteorite</button></div>","<div><button  class='primary-button'>c). Meteor</button></div>","<div><button  class='primary-button'>d). Comet</button></div>", "Description: Meteoroids are objects in space that range in size from dust grains to small asteroids. Think of them as 'space rocks.' When meteoroids enter Earth’s atmosphere (or that of another planet, like Mars) at high speed and burn up, the fireballs or “shooting stars” are called meteors. When a meteoroid survives a trip through the atmosphere and hits the ground, it’s called a meteorite."],
["<h4> Why does the Sun look small in the sky to us?</h4>", "<div><button  class='primary-button'>a). Its not very bright.</button></div>", "<div><button  class='primary-button'>b). Its smaller than Earth.</button></div>","<div><button  class='primary-button-correct'> c). Its  93000000 miles away from Earth.</button></div>","<div><button  class='primary-button'>d). It travels around the Earth.</button></div>", "Description: The further the object the smaller it looks."],
["<h4> Kuiper belt houses which astronomical object of our Solar System?</h4>", "<div><button  class='primary-button'>a). Comets</button></div>", "<div><button  class='primary-button'>b). Meteorite</button></div>","<div><button  class='primary-button-correct'>c). Pluto</button></div>","<div><button  class='primary-button'>d). Stars</button></div>", "Description: Pluto lies outside the orbit of Neptune in the Kuiper belt."],
["<h4> What is the best way to describe the location of our Solar System?</h4>", "<div><button  class='primary-button'>a). It’s located in a galaxy known as ‘local group’.</button></div>", "<div><button  class='primary-button-correct'>b). It’s located in a galaxy known as ‘Milky way galaxy’, which is a part of a cluster ‘Local group’.</button></div>","<div><button  class='primary-button'>c). It’s located in a galaxy known as ‘Milky way galaxy’, which is not a  part of a cluster ‘Local group’.</button></div>","<div><button  class='primary-button'>d). Centre of Earth.</button></div>", "Description: A galaxy is a cluster of Stars and some of these stars have planets revolving them making a solar System. A cluster is a group of galaxies. So our solar system is a part of Milky-Way Galaxy which is part of a cluster called 'Local Group'  "],
["<h4> Which is the brightest planet in our Solar System?</h4>", "<div><button  class='primary-button-correct'>a). Venus</button></div>", "<div><button  class='primary-button'>b). Mercury</button></div>","<div><button  class='primary-button'>c). Earth</button></div>","<div><button  class='primary-button'>d). Saturn</button></div>", "Description: Venus's atmosphere is composed of gases which reflect light very easily. This leads Venus to reflect nearly 70% of light it gets fom sun, thus making it look so bright."],
["<h4> Which is the nearest planet to the sun?</h4>", "<div><button  class='primary-button'>a). Neptune</button></div>", "<div><button  class='primary-button'>b). Mars</button></div>","<div><button  class='primary-button-correct'>c). Mercury</button></div>","<div><button  class='primary-button'>d). Earth</button></div>", "Description: Mercury is the nearest planet to the sun."],
["<h4> Which is the largest planet in solar system?</h4>", "<div><button  class='primary-button'>a). Mars</button></div>", "<div><button  class='primary-button'>b). Uranus</button></div>","<div><button  class='primary-button'>c). Saturn</button></div>","<div><button  class='primary-button-correct'>d). Jupiter</button></div>", "Description: Jupiter is the largest planet in our solar system, but it is largely made up of gases which leads to its low density."],
["<h4> Which is the first planet outside Earth's orbit?</h4>", "<div><button  class='primary-button'>a). Jupiter</button></div>", "<div><button  class='primary-button-correct'>b). Mars</button></div>","<div><button  class='primary-button'>c). Mercury</button></div>","<div><button  class='primary-button'>d). Neptune</button></div>", "Description: In order of their distance from sun, Earth comes at 3rd position and Mars comes at 4th."],
["<h4> Which is a gaseous planet?</h4>", "<div><button  class='primary-button-correct'>a). Saturn</button></div>", "<div><button  class='primary-button'>b). Venus</button></div>","<div><button  class='primary-button'>c). Mars</button></div>","<div><button  class='primary-button'>d). Mercury</button></div>", "Description: Saturn is a gaseous planet. Its very large compared to other planets but its gaseous composition causes its density to be very low. Fun Fact Saturn's density is so low that it can float on water."],

                ];


var inQue="<div class='text-content'>  "+ queText[rarray[0]][0]+queText[rarray[0]][1]+queText[rarray[0]][2]+queText[rarray[0]][3]+queText[rarray[0]][4]+"<div class='explain'> </div> </div> "; document.querySelector('#Q1').innerHTML= inQue;
inQue="<div class='text-content'>  "+ queText[rarray[1]][0]+queText[rarray[1]][1]+queText[rarray[1]][2]+queText[rarray[1]][3]+queText[rarray[1]][4]+"<div class='explain'> </div> </div> "; document.querySelector('#Q2').innerHTML= inQue;
inQue="<div class='text-content'>  "+ queText[rarray[2]][0]+queText[rarray[2]][1]+queText[rarray[2]][2]+queText[rarray[2]][3]+queText[rarray[2]][4]+"<div class='explain'> </div> </div> "; document.querySelector('#Q3').innerHTML= inQue;
inQue="<div class='text-content'>  "+ queText[rarray[3]][0]+queText[rarray[3]][1]+queText[rarray[3]][2]+queText[rarray[3]][3]+queText[rarray[3]][4]+"<div class='explain'> </div> </div> "; document.querySelector('#Q4').innerHTML= inQue;
inQue="<div class='text-content'>  "+ queText[rarray[4]][0]+queText[rarray[4]][1]+queText[rarray[4]][2]+queText[rarray[4]][3]+queText[rarray[4]][4]+"<div class='explain'> </div> </div> "; document.querySelector('#Q5').innerHTML= inQue;